const ROUTES = {
	SIGN_UP: '/profiler/signup',
	LOGIN: '/profiler/login',
	SERVICE_METRICS: '/profiler/services/:servicename',
	SERVICE_MAP: '/profiler/service-map',
	TRACE: '/profiler/trace',
	TRACE_DETAIL: '/profiler/trace/:id',
	TRACES_EXPLORER: '/profiler/traces-explorer',
	SETTINGS: '/profiler/settings',
	GET_STARTED: '/profiler/get-started',
	USAGE_EXPLORER: '/profiler/usage-explorer',
	APPLICATION: '/profiler/services',
	ALL_DASHBOARD: '/profiler/dashboard',
	DASHBOARD: '/profiler/dashboard/:dashboardId',
	DASHBOARD_WIDGET: '/profiler/dashboard/:dashboardId/:widgetId',
	EDIT_ALERTS: '/profiler/alerts/edit',
	LIST_ALL_ALERT: '/profiler/alerts',
	ALERTS_NEW: '/profiler/alerts/new',
	ALL_CHANNELS: '/profiler/settings/channels',
	CHANNELS_NEW: '/profiler/settings/channels/new',
	CHANNELS_EDIT: '/profiler/settings/channels/:id',
	ALL_ERROR: '/profiler/exceptions',
	ERROR_DETAIL: '/profiler/error-detail',
	VERSION: '/profiler/status',
	MY_SETTINGS: '/profiler/my-settings',
	ORG_SETTINGS: '/profiler/settings/org-settings',
	INGESTION_SETTINGS: '/profiler/settings/ingestion-settings',
	SOMETHING_WENT_WRONG: '/profiler/something-went-wrong',
	UN_AUTHORIZED: '/profiler/un-authorized',
	NOT_FOUND: '/profiler/not-found',
	LOGS: '/profiler/logs',
	LOGS_EXPLORER: '/profiler/logs-explorer',
	LIVE_LOGS: '/profiler/logs-explorer/live',
	LOGS_PIPELINES: '/profiler/pipelines',
	HOME_PAGE: '/profiler/',
	PASSWORD_RESET: '/profiler/password-reset',
	LIST_LICENSES: '/profiler/licenses',
	LOGS_INDEX_FIELDS: '/profiler/logs-explorer/index-fields',
	TRACE_EXPLORER: '/profiler/trace-explorer',
	BILLING: '/profiler/billing',
	SUPPORT: '/profiler/support',
	WORKSPACE_LOCKED: '/profiler/workspace-locked',
};

export default ROUTES;
